### ISSUE TITLE
Cannot add group to site in Alfresco 7.3

### ISSUE THREAD

**Issue by nschwalbe** [Alfresco/collaborating-with-alfresco#5]
### Summary
The search for groups on the add site member page returns always an empty result set.

### Affected versions

Tested with
- Repository 7.2.1, Share 7.2.1.6
- Repository 7.3.0, Share 7.3.0.2

The last version it worked for me was 7.1.1

### Reproduce

Open http://localhost:8080/share/page/site/swsdp/add-groups

Enter `a` and click the search button.
=> No results

### Expected results
At least the default `ALFRESCO_` groups should be found.

**Comment by nschwalbe** [comment]
In 7.3.1 it is fixed.

**Comment by p4535992** [comment]
Close the ticket if is solved
